config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "curricula#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :curricula
  resources :lessons
  resources :cards, only: %i[new] do
    member do
      patch :attempt
      get :bookmark
    end
  end

  get ":mode/card/:id", to: 'cards#show', as: :card, mode: /learning|test/
  resources  :bookmarks, only: %i[index]
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @curricula = Curriculum
                 .where(user: current_user)
                 .reject { |curriculum| curriculum.bookmarks.empty? }
  end
end

app/views/bookmarks/_bookmark.html.erb
<%= link_to card_path(mode:'learning', id: bookmark.id), class:"text-decoration-none" do %>
  <div class="d-flex mt-2 rounded-3 shadow-sm border p-4 bg-cream">
    <span><%= lucide_icon('bookmark-check') %></span>
    <span class="flex-grow-1 mx-2"><%= bookmark.instruction %></span>
    <span class="badge rounded-pill bg-purple d-flex align-items-center">
      <%= bookmark.card_template.name %>
    </span>
  </div>
<% end  %>

app/views/bookmarks/index.html.erb
<% if @curricula.empty? %>
  <div class="d-flex align-items-center justify-content-center border rounded-5 w-100 shadow bg-white" style="height: 450px">
    <div>
      <p class="fs-3">You have no bookmarked cards</p>
      <%= link_to "Back to \"My Curricula\"", curricula_path, class:"d-block text-center fs-5 btn btn-primary bg-dark-blue rounded-5" %>
    </div>
  </div>
<% else %>
  <div class="d-flex position-relative">
    <%# quick navigation links on the left %>
    <div class="position-sticky top-0">
      <div class="position-sticky top-nav-4 me-4" style="max-width: 300px;">
        <h1>My Bookmarks</h1>
        <ol>
          <% @curricula.each do |curriculum| %>
            <li>
              <%=
                link_to(
                  "#{curriculum.title} (#{curriculum.bookmarks.length})",
                  "##{curriculum.title.downcase.gsub(/\s+/, '-')}",
                  class: "text-decoration-none d-block"
                )
              %>
            </li>
          <% end %>
        </ol>
      </div>
    </div>
    <%# bookmarks on the right %>
    <div class="position-relative flex-grow-1">
      <% @curricula.each_with_index do |curriculum, i| %>
        <div class="<%= i > 0 ? 'mt-3' : '' %>">
          <h2 id=<%= curriculum.title.downcase.gsub(/\s+/, '-') %>>
            <%= curriculum.title %>
          </h2>
          <% curriculum.lessons_with_bookmarks.each_with_index do |lesson, j| %>
            <div class="<%= j > 0 ? 'mt-3' : '' %>">
              <h3><%= lesson.title %></h3>
              <% lesson.bookmarks.each do |bookmark| %>
                <%= render "bookmark", bookmark: bookmark %>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>