config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "curricula#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :curricula
  resources :lessons
  resources :cards, only: %i[new] do
    member do
      patch :attempt
      get :bookmark
    end
  end

  get ":mode/card/:id", to: 'cards#show', as: :card, mode: /learning|test/
  resources  :bookmarks, only: %i[index]
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :card_template
  belongs_to :lesson
  has_many :options, dependent: :destroy

  has_one_attached :picture
  has_one_attached :audio

  validates :instruction, :model_answer, presence: true

  before_validation :check_empty
  before_save :score!, if: :will_save_change_to_user_answer?

  # after_save :clear_tmp_file

  LEARNING_TEMPLATES = [
    "Listening Comprehension",
    "MCQ",
    "Translate"
  ]

  def attempted?
    # [true, false].include?(correct)
    !correct.nil?
  end

  # called after user has submitted user_answer
  # call API if image_comprehension
  # check against model_answer for everything else
  # updates :correct
  def score!
    if card_template.name == "Picture Comprehension"
      CardScoringJob.perform_later(id, user_answer, model_answer)
    else
      self.correct = direct_comparison
    end
  end

  def calculating_score?
    !user_answer.nil? && correct.nil?
  end

  def learn?
    LEARNING_TEMPLATES.include? card_template.name
  end

  def broadcast_score
    broadcast_replace_to "thumbnails",
                         partial: "cards/thumbnail",
                         target: "thumb_#{id}",
                         locals: { card: self }
  end

  private

  def check_empty
    self.user_answer = nil if user_answer == ""
  end

  # For a MCQ question, this is the scoring method:
  def direct_comparison
    user_answer == model_answer
  end

  # For a Picture Comprehension question, this is the scoring method:
  def similarity_comparison
    CardScoringJob.perform_later(id, user_answer, model_answer)
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[show update bookmark attempt]

  def show
    @mode = params[:mode]
    @next_card = @card.lesson.next_card(@mode, @card)
  end

  def attempt
    @card.user_answer = card_params[:user_answer]

    if @card.save
      next_card = @card.lesson.next_card("test", @card, true)

      redirect_to next_card.nil? ? @card.lesson : card_path("test", next_card)
    else
      render :show, status: :unprocessable_entity
    end
  end

  def update; end

  def bookmark
    @card.bookmarked = !@card.bookmarked
    @card.save
    redirect_to card_path(params[:mode], @card)
  end

  private

  def set_card
    @card = Card.find(params[:id])
    template_name = @card.card_template.name.downcase.gsub(' ', '_')
    @template_path = "cards/templates/#{template_name}"
  end

  def card_params
    params.require(:card).permit(:user_answer)
  end
end

app/views/cards/templates/_listening_comprehension.html.erb
<div class="context border border-3 rounded p-5 mt-5 mb-5 banner-background">
  <audio src='<%= card.audio.url %>' controls preload='auto'></audio>
</div>

<% if mode == 'learning' %>
    <%= card.model_answer %>
  <div class="view-curriculum-btn w-25 m-auto">
    <%= link_to 'Next', next_card.nil? ? card.lesson : card_path("learning", next_card), class:"text-white" %>
  </div>
<% else %>
  <p><%= card.instruction %></p>
  <div class="text-center">
    <%= simple_form_for card, url: attempt_card_path(card) do |f| %>
      <%= f.input :user_answer, label: false %>
      <%= f.submit "Answer" %>
    <% end %>
  </div>
<% end %>

app/views/cards/templates/_mcq.html.erb
<div class="context border border-3 rounded p-5 mt-5 mb-5 banner-background">
  <% if card.picture.attached?  %>
    <%= render cl_image_tag @card.picture.key, height: 300, width: 400, crop: :fill %>
  <% elsif card.audio.attached? %>
    <%= render cl_video_tag @card.audio.key %>
  <% else %>
    <%= card.context %>
  <% end %>
</div>
<% if mode == "learning" %>
  <%= card.model_answer %>
  <div class="view-curriculum-btn w-25 m-auto">
    <%= link_to 'Next', next_card.nil? ? card.lesson : card_path("learning", next_card), class:"text-white" %>
  </div>
<% else %>
  <div class="text-center">
    <%# <label for="options"></label> %>
    <input type="radio">
    <%= simple_form_for @card, url: attempt_card_path(@card) do |f| %>
      <div class="grid-style">
        <%= f.collection_radio_buttons :user_answer, @card.options.map { |option| [option.content, option.content] }, :first, :last, item_label_class: 'mcq' %>
      </div>
      <%= f.submit "Answer" %>
    <% end %>
  </div>
<% end %>

app/views/cards/templates/_picture_comprehension.html.erb
<div class="context border border-3 rounded p-5 mt-5 mb-5" >
  <p><%= cl_image_tag @card.picture.key, height: 300, width: 400, crop: :fill %></p>
</div>

  <div class="text-center">
    <%= simple_form_for @card, url: attempt_card_path(@card) do  |f| %>
      <%= f.input :user_answer, label: false %>
      <%= f.submit "Answer" %>
    <% end %>
  </div>

app/views/cards/templates/_translate.html.erb
<div class="context border border-3 rounded p-5 mt-5 mb-5 banner-background">
  <p><%= @card.context %></p>
</div>

<% if mode == "learning" %>
    <%= card.model_answer %>
  <div class="view-curriculum-btn w-25 m-auto">
    <%= link_to 'Next', next_card.nil? ? card.lesson : card_path("learning", next_card), class:"text-white" %>
  </div>
<% else %>
  <div class="text-center">
      <%= simple_form_for @card, url: attempt_card_path(@card) do |f| %>
        <%= f.input :user_answer, label: false %>
        <%= f.submit "Answer" %>
      <% end %>
  </div>
<% end %>