config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "curricula#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :curricula
  resources :lessons
  resources :cards, only: %i[new] do
    member do
      patch :attempt
      get :bookmark
    end
  end

  get ":mode/card/:id", to: 'cards#show', as: :card, mode: /learning|test/
  resources  :bookmarks, only: %i[index]
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :curriculum
  has_many :cards, dependent: :destroy

  validates :title, :description, :order, presence: true

  def first_card
    cards.order(:id).first
  end

  def next_lesson
    curriculum.lessons.find_by(order: order + 1)
  end

  def status
    completed = cards.pluck(:correct)

    if completed.all?(&:nil?)
      "pending"
    elsif completed.any?(&:nil?)
      "started"
    else
      "completed"
    end
  end

  # find the first card in the lesson where the
  # correct key is nil. This would represent the
  # "next" card.
  # if card is passed as an argument, return the
  # next card from that provided card
  def next_card(mode, card = nil, include_answered = false)
    cardset = include_answered ? cards.order(:id) : cards.where(correct: nil).order(:id)

    if mode == 'learning' && status != "completed"
      cardset = cardset.select do |c|
        Card::LEARNING_TEMPLATES.include?(c.card_template.name)
      end
    end

    if card.nil?
      cardset.first
    else
      index = cardset.find_index(card)
      index.nil? ? cardset.first : cardset[index + 1]
    end
  end

  def score
    correct = cards.where(correct: true).length
    wrong = cards.where(correct: false).length
    (correct + wrong).positive? ? correct.to_f / (correct + wrong) : 0
  end

  def progress
    cards.empty? ? 0 : cards.reject { |card| card.correct.nil? }.length.to_f / cards.length
  end

  def completed_cards
    cards.where.not(correct: nil)
  end

  def incomplete_cards
    cards.where(correct: nil)
  end

  def bookmarks
    cards.where(bookmarked: true)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def show
    @lesson = Lesson.find(params[:id])

    @cards = @lesson.cards
    @cards = @cards.where(correct: true) if params[:cards] == "correct"
    @cards = @cards.where(correct: false) if params[:cards] == "mistakes"
    @mode = params[:mode] || "learning"
  end

  def update
    @lesson = Lesson.find(params[:id])
    @lesson = update(lesson_params)
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
  end

  private

  def lesson_params
    params.require(:lesson).permit(:title, :description, :score, :progress)
  end
end

app/views/lessons/_bookmarked_preview.html.erb
<div>
  <div class="d-flex border px-3">
    <p class="ms-3 my-0 py-3"><i class="fa-solid fa-bookmark"></i> <%= card.instruction %></p>
  </div>
</div>

app/views/lessons/_card_preview.html.erb
<div class="cards-content d-flex border justify-content-between p-3 shadow rounded">
  <div class="left-side">
    <div class="bookmark-icon" style="width: 2rem; display: inline-block;">
      <%= lucide_icon('bookmark-check') if card.bookmarked %>
    </div>
    <%= link_to "#{card.instruction}", card_path("test", card.id) %>
  </div>
  <div class="right-side d-flex gap-5">
    <div text-align="center" style="width: 12rem;">
      <p class="badge rounded-pill <%= "pill-#{card.card_template.name.downcase.gsub(" ", "-")}" %> "> <%= card.card_template.name %></p>
    </div>
    <p><% if card.correct == true %>
        <i class="fa-regular fa-circle-check text-success"></i>
      <% elsif card.correct.nil? %>
        <i class="fa-regular fa-question-circle"></i>
      <% else %>
        <i class="fa-regular fa-circle-xmark text-danger"></i>
      <% end %>
    </p>
  </div>
</div>

app/views/lessons/_correct_filter.html.erb
<%= link_to card_path(card), class:"lesson-card" do %>
  <div class="d-flex border px-3 justify-content-between">
      <% if card.bookmarked == true %>
        <%= lucide_icon('bookmark-check') %>
      <% else %>
        <%= lucide_icon('bookmark') %>
      <% end %>
        <p class="ms-3 my-0 py-3"><%= card.instruction %></p>
        <p class="ms-3 my-0 py-3"><%= card.card_template.name %></p>
    <p class="ms-3 my-0 py-3">
      <% if card.correct == true %>
        <i class="fa-regular fa-circle-check text-success"></i>
      <% end %>
    </p>
  </div>
<% end %>

app/views/lessons/_mistake_filter.html.erb
<%= link_to card_path(card), class:"lesson-card" do %>
  <div class="d-flex border px-3 justify-content-between">
      <% if card.bookmarked == true %>
        <%= lucide_icon('bookmark-check') %>
      <% else %>
        <%= lucide_icon('bookmark') %>
      <% end %>
        <p class="ms-3 my-0 py-3"><%= card.instruction %></p>
        <p class="ms-3 my-0 py-3"><%= card.card_template.name %></p>
    <p class="ms-3 my-0 py-3">
      <% if card.correct == false %>
        <i class="fa-regular fa-circle-xmark text-danger"></i>
      <% end %>
    </p>
  </div>
<% end %>

app/views/lessons/_summary.html.erb
<div>
    <%= card %>
</div>

app/views/lessons/show.html.erb
<div class="container">

  <div class="d-flex p-3 m-5 border shadow-sm rounded">
    <div class="col-10">
      <div class="back p-2">
        <%= link_to "< Back to #{@lesson.curriculum.title}", curriculum_path(@lesson.curriculum) %>
      </div>
      <div class="lesson-title p-2">
        <h1><%= @lesson.title %> <%= @mode == "learning" ? ": Learning Mode" : ": Quiz Mode" %> </h1>
      </div>
      <div class="lesson-description p-2">
        <p><%= @lesson.description %></p>
      </div>
      <div class="d-flex p-2 gap-2">
        <%= link_to 'Learn 👩🏻‍🎓', card_path('learning', @lesson.first_card), class: 'btn btn-learn border-radius rounded-pill' %>
        <% if @lesson.status != "completed" %>
          <% if @lesson.status == 'pending' %>
            <%= link_to 'Begin quiz', card_path('test', @lesson.next_card("test")), class: 'btn btn-quiz border-radius rounded-pill' %>
          <% else %>
            <%= link_to 'Resume quiz', card_path('test', @lesson.next_card("test")), class: 'btn btn-quiz border-radius rounded-pill' %>
          <% end %>
        <% end %>
        <% if @lesson.next_lesson %>
          <%= link_to 'Next lesson', lesson_path(@lesson.next_lesson), class: 'btn btn-quiz border-radius rounded-pill' if @lesson.status == 'completed' %>
        <% end %>
      </div>
    </div>

    <div class="col-2">
      <div class="position-relative" style="width: 12rem; height: 12rem;">
        <canvas
              data-controller="doughnut-progress-chart"
              data-doughnut-progress-chart-input-value="[<%= @lesson.completed_cards.length %>,<%= @lesson.incomplete_cards.length %>]"
              data-doughnut-progress-chart-colors-value='["rgb(72, 156, 150)", "rgb(255, 255, 255)"]'
            ></canvas>
        <div class="position-absolute top-50 start-50 translate-middle">
          <p class="mt-4 fs-5"><%= (@lesson.progress * 100).ceil %>%</p>
        </div>
      </div>
    </div>
  </div>

  <div class="cards-info-wrapper m-5">
    <!-- Card Header -->
    <div class="d-flex justify-content-between m-3">
      <div class="header-and-add-custom-card d-flex gap-2">
        <h2>Cards</h2>
      </div>
      <div class="d-flex">
        <%
          is_correct = params[:cards] == "correct"
          is_mistakes = params[:cards] == "mistakes"
          is_all = !is_correct && !is_mistakes
        %>
        <%= link_to "All", lesson_path(@lesson), class: "px-1 #{is_all ? "text-decoration-underline" : ""}" %> |
        <%= link_to "Correct", lesson_path(@lesson, cards: "correct"), class:"px-1 #{is_correct ? "text-decoration-underline" : ""}" %> |
        <%= link_to "Mistakes", lesson_path(@lesson, cards: "mistakes"), class: "px-1 #{is_mistakes ? "text-decoration-underline" : ""}" %>
      </div>
    </div>

    <!-- Cards -->
    <div class="cards-content-wrapper p-3 d-grid gap-3">
      <% @cards.order(:id).each do |card| %>
        <%= render 'card_preview', card: card %>
      <% end %>
    </div>

  </div>
</div>