config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "curricula#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :curricula
  resources :lessons
  resources :cards, only: %i[new] do
    member do
      patch :attempt
      get :bookmark
    end
  end

  get ":mode/card/:id", to: 'cards#show', as: :card, mode: /learning|test/
  resources  :bookmarks, only: %i[index]
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :card_template
  belongs_to :lesson
  has_many :options, dependent: :destroy

  has_one_attached :picture
  has_one_attached :audio

  validates :instruction, :model_answer, presence: true

  before_validation :check_empty
  before_save :score!, if: :will_save_change_to_user_answer?

  # after_save :clear_tmp_file

  LEARNING_TEMPLATES = [
    "Listening Comprehension",
    "MCQ",
    "Translate"
  ]

  def attempted?
    # [true, false].include?(correct)
    !correct.nil?
  end

  # called after user has submitted user_answer
  # call API if image_comprehension
  # check against model_answer for everything else
  # updates :correct
  def score!
    if card_template.name == "Picture Comprehension"
      CardScoringJob.perform_later(id, user_answer, model_answer)
    else
      self.correct = direct_comparison
    end
  end

  def calculating_score?
    !user_answer.nil? && correct.nil?
  end

  def learn?
    LEARNING_TEMPLATES.include? card_template.name
  end

  def broadcast_score
    broadcast_replace_to "thumbnails",
                         partial: "cards/thumbnail",
                         target: "thumb_#{id}",
                         locals: { card: self }
  end

  private

  def check_empty
    self.user_answer = nil if user_answer == ""
  end

  # For a MCQ question, this is the scoring method:
  def direct_comparison
    user_answer == model_answer
  end

  # For a Picture Comprehension question, this is the scoring method:
  def similarity_comparison
    CardScoringJob.perform_later(id, user_answer, model_answer)
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[show update bookmark attempt]

  def show
    @mode = params[:mode]
    @next_card = @card.lesson.next_card(@mode, @card)
  end

  def attempt
    @card.user_answer = card_params[:user_answer]

    if @card.save
      next_card = @card.lesson.next_card("test", @card, true)

      redirect_to next_card.nil? ? @card.lesson : card_path("test", next_card)
    else
      render :show, status: :unprocessable_entity
    end
  end

  def update; end

  def bookmark
    @card.bookmarked = !@card.bookmarked
    @card.save
    redirect_to card_path(params[:mode], @card)
  end

  private

  def set_card
    @card = Card.find(params[:id])
    template_name = @card.card_template.name.downcase.gsub(' ', '_')
    @template_path = "cards/templates/#{template_name}"
  end

  def card_params
    params.require(:card).permit(:user_answer)
  end
end

app/views/cards/_listening_comprehension_template.html.erb
<%# Example instruction: 'Type what you hear'%>

<h3><%= @card.instruction %></h3>
<div class="context border border-3 rounded p-5 mt-5 mb-5">
  <p><%= @card.context %></p>
</div>
<p class="border border-3 rounded-pill p-2"><%= @card.answer %></p>

app/views/cards/_picture_comprehension_template.html.erb
<%# Example instruction: 'Describe the following image'%>

<h3><%= @card.instruction %></h3>
<div class="context border border-3 rounded p-5 mt-5 mb-5">
  <p><%= cl_image_tag ("picture_comprehension_example"), height: 300, width: 400, crop: :fill %></p>
</div>
<p class="border border-3 rounded-pill p-2"><%= @card.answer %></p>

app/views/cards/_thumbnail.html.erb
<%= link_to card_path(params[:mode], card) do %>
  <div id="thumb_<%= card.id %>" class="px-1 <%= "active" if params[:id].to_i == card.id %>">
    <% if card.correct %>
      🟢
    <% elsif card.correct == false %>
      🔴
    <% elsif card.calculating_score? %>
      <%= lucide_icon("loader") %>
    <% else %>
      ⚪️
    <% end %>
  </div>
<% end %>

app/views/cards/_translate_template.html.erb
<%# Example instruction: 'Translate the following sentence'%>

<h3><%= @card.instruction %></h3>
<div class="context border border-3 rounded p-5 mt-5 mb-5">
  <p><%= @card.context %></p>
</div>
<p class="border border-3 rounded-pill p-2"><%= @card.answer %></p>

app/views/cards/show.html.erb
<div class="d-flex justify-content-between p-5">
  <div class="back-to-lesson"><%= link_to 'Back to lesson', lesson_path(@card.lesson)%></div>
  <div class="bookmark-icon">
  <%= link_to bookmark_card_path(@card, mode: @mode), class: "text-decoration-none" do %>
    <% if @card.bookmarked %>
      Bookmarked <%= lucide_icon('bookmark-check') %>
    <% else %>
      Add to bookmarks <%= lucide_icon('bookmark') %>
    <% end %>
  <% end %>
  </div>

</div>

<div class="container text-center">
  <div class="card-content">
    <%# render partials of templates here%>
    <h3><%= @card.instruction %></h3>
    <%= render @template_path, card: @card, mode: @mode, next_card: @next_card %>
  </div>


  <% if @mode == "test" %>
    <%= turbo_stream_from "thumbnails" %>
    <div class="thumbnails d-flex justify-content-center mt-3">
      <% @card.lesson.cards.order(:id).each do |card| %>
          <%= render 'cards/thumbnail', card: card %>
      <% end %>
    </div>
  <% end %>
</div>